apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-api
  template:
    metadata:
      labels:
        app: diabetes-api
    spec:
      containers:
      - name: diabetes-container
        image: diabetes-api:latest
        imagePullPolicy: Never    # 👈 ensures it uses local Minikube image
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-service
spec:
  type: ClusterIP
  selector:
    app: diabetes-api
  ports:
    - port: 8000
      targetPort: 8000
